name: Update Arch User Repository Every week
on: 
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:
jobs:
  update-repos:
    runs-on: ubuntu-latest
    outputs:
        changes_committed: ${{ steps.check_changes.outputs.changes_committed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CR_PAT}}
      - name: Update all submodules
        run: |
            git submodule foreach --recursive git pull origin master
      - name: Commit and push changes
        id: check_changes
        run: |
          git config --global user.email "84152320+github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add .
          if git diff-index --quiet HEAD; then
              echo "No changes to commit"
              echo "::set-output name=changes_committed::false"
          else
              git commit -m "Update AUR submodules"
              git push origin master
              echo "::set-output name=changes_committed::true"
          fi

  trigger-build:
    runs-on: ubuntu-latest
    needs: update-repos
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Trigger the Build Workflow
        uses: actions/github-script@v7
        id: trigger_build
        with:
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build.yml',
            ref: 'master'
            });
            console.log(result);
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification on Success
        if: success()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          slack-message: |
            Build workflow has been triggered successfully
            Job: ${{ github.job }}
            Workflow: ${{ github.workflow }}
            Commit: ${{ github.sha }}
            Triggered by: ${{ github.actor }}
            See the details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_NAME: "GitHub Actions"
      - name: Slack Notification on Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          slack-message: |
            Build workflow has failed
            Job: ${{ github.job }}
            Error: ${{ steps.trigger_build.conclusion }} - ${{ steps.trigger_build.outcome }}
            See the logs for more details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_NAME: "GitHub Actions"
